name: Build EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install libs
      run: pip install pyinstaller requests

    - name: Build EXE
      run: pyinstaller --onefile --noconsole tool_vip.py

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: earnapp-exe
        path: dist/*.exe
